//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NavtechAssesment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string OrderName { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string OrderStatus { get; set; }
        public string OrderDetails { get; set; }
        public string ShippingAddress { get; set; }
    }
}
